#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# Run tests before push
echo '------------------------------------------------------'
echo '|                    run run test                    |'
echo -n '------------------------------------------------------'
npm run test
