#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# Check code formatting
echo '------------------------------------------------------'
echo '|                    npm run format                  |'
echo -n '------------------------------------------------------'
npm run format
